### PR TITLE
Fix various typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via codespell v2.1.dev0  
`codespell -q 3 -L ans,filp,fils,hsi`

### CODE REVIEW

**Comment by luzpaz** [comment]
Please review 7bfc072 closely

**Comment by JiaoXianjun** [comment]
So, the patches are generated automatically by the codespell tool by scanning all files in our repository?

**Comment by luzpaz** [comment]
No, I tailored them.

**Comment by JiaoXianjun** [comment]
Thanks. 
For the text in document and comment, I will take them.
For the change in the code, currently I will leave them as they are. Because they are from Analog Devices and Xilinx, we don't want to take the risk and do a complete test right now.

**Comment by luzpaz** [comment]
Sounds good. Maybe you want to archive the fixes that you want to implement later? It's your call.

**Comment by luzpaz** [comment]
Feel free to cherrypick the commit you want.

**Comment by JiaoXianjun** [comment]
done

**Pull request closed without merging**
