### PR TITLE
MicroPhase new product ANTSDR-E200 support openwifi

### PR DESCRIPTION
**Pull request by MicroPhase**
hello,
We have a new product antsdr_e200 now can support openwifi. If you want to find some information about this product, please refer to the readme file at the kernel_boot/boards/antsdr_e200.

### CODE REVIEW

**Comment by MicroPhase** [comment]
There is still some bugs, close this pr.

**Comment by JiaoXianjun** [comment]
Could you check the issue I encountered in the openwifi-hw pull request?

**Comment by JiaoXianjun** [comment]
Suggestion: make all commits into 1
Question:

You mean for antsdr_e200, the kernel config has to be:
CONFIG_DEBUG_ZYNQ_UART0=y
# CONFIG_DEBUG_ZYNQ_UART1 is not set

For other boards, it has to be:
# CONFIG_DEBUG_ZYNQ_UART0 is not set
CONFIG_DEBUG_ZYNQ_UART1=y

?

We prefer to use one kernel config/image for all boards. Is there a way to use the same kernel config (with necessary change) for all boards (including antsdr_e200)? Such as, changing FPGA, or ARM config, or devicetree?

**Comment by black-pigeon** [comment]
The antsdr_e200's uart is located at PS MIO 14...15, which will use uart0 controller, other devices using uart1 controller.

**Comment by JiaoXianjun** [comment]
Can it be solved by the kernel parameter (while loaded by u-boot) instead of kernel config?

**Comment by black-pigeon** [comment]
We will try and request a new P&R if we have some good news.

**Comment by MicroPhase** [comment]
Close this PR.
We will update this soon.

**Pull request closed without merging**
