### PR TITLE
Pull the 802.11n

### PR DESCRIPTION
**Pull request by Leo-Cheung-CUHK**

### CODE REVIEW

**Comment by JiaoXianjun** [comment]
Hi,

For commit: dd37174259e695e29283d109322491bf34b7bcd8:
The readme change is not necessary, because we already solve the issue.

**Comment by JiaoXianjun** [comment]
For the other two commits, seems like it is about TDMA support.

It is really an interesting feature, and we are very glad to see that there is the first new feature from the community! Thanks a lot!

Is there any simple document to explain the concept and the related modification? Then we can understand well about your modifications, and decide how to proceed.

And since our master has updated, if you could come up with a new pull request based on our latest master, that will be better.

Thanks!

**Comment by Leo-Cheung-CUHK** [comment]
Xianjun, 

Nice to see your comments. I developed a simple TDMA scheme by changing both software and hardware. In short, some TDMA related information is stored and broadcasted using a beacon (That is why I tried to customize the beacon). Meanwhile, on hardware, we need to develop two main features, namely, time-synchronization and time-slotted transmission. Time-synchronization can simply be achieved by using the TSF scheme (although this scheme provides only around 20 microseconds of precision). Time-slotted transmission can be achieved by replacing the CSMA module with a TDMA module. 

I will come up with a new pull request and let you know ASAP.

Best,
Lihao

**Comment by JiaoXianjun** [comment]
Thanks.

Some suggestions:

1. For the function and variable naming, please avoid my_xxxx style. Instead, name it with more meaningful word.
2. For the TDMA related test/setup/(turn on/enable method, turn off/disable method, etc) command you put into the README, would you please write an application notes here: https://github.com/open-sdr/openwifi/tree/master/doc/app_notes . Then we can keep README as simple as possible (it is already very long)

Thanks!

**Comment by Leo-Cheung-CUHK** [comment]
I see. Thanks for your kind suggestions; I will follow them. 

Lihao

**Comment by 18845725896peng** [comment]
Can you tell me how to use the TSF scheme to Realize time synchronization？

**Pull request closed without merging**
